name: Deploy to Fly.io
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: blacksmith-4vcpu-ubuntu-2204
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
